basePath: /
definitions:
  dto.ErrorResponseDTO:
    properties:
      error:
        type: string
    type: object
  dto.LoginUserDTO:
    properties:
      password:
        maxLength: 25
        minLength: 8
        type: string
      username:
        maxLength: 25
        minLength: 8
        type: string
    required:
    - password
    - username
    type: object
  dto.MessageResponseDTO:
    properties:
      message:
        type: string
    type: object
host: localhost:port
info:
  contact: {}
  description: api for a portfolio project
  title: Backend Portfolio API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: user data
        in: body
        name: guest
        required: true
        schema:
          $ref: '#/definitions/dto.LoginUserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.MessageResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      tags:
      - users
swagger: "2.0"
